---

services:
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    image: ai
    container_name: ai
    restart: always
    ports:
      - 8888:8888
    networks:
      - ai-network
      - ai-db-network
    depends_on:
        cassandra:
          condition: service_healthy
  
  dataingestor:
    build:
      context: ./ai_data_injector
      dockerfile: Dockerfile
    environment:
      - CassandraUserName=cassandra
      - CassandraPassword=cassandra
      - CassandraSystemMaintenanceKeyspace=systemdata
      - MessageUrl=amqp://guest:guest@localhost:5672/
    image: dataingestor
    container_name: dataingestor
    restart: always
    networks:
      - ai-network
      - ai-db-network
    depends_on:
      cassandra:
        condition: service_healthy
  
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ai-cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - ai-network
      - ai-db-network

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./ai_data_injector/DataSchema/Cassandra_Schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
    networks:
      - ai-db-network