---
version: '3'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: webapp
    container_name: webapp
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - app-network
      - api-network