---
version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SpPassKey=Test2Alpha1234!
      - MongoDbConnectionString=mongodb://root:example@mongo:27017/
      - MongoDbDatabaseName=encryption
      - RedisHostName=redis
      - RedisPortNumber=6379
      - RedisPassword=Romeo1Sierra@Zulu
      - SecuredRedisHostName=sec-redis
      - SecuredRedisPortNumber=10500
      - SecuredRedisPassword=LimaOmaha34#
      - SQLServerHostname=db
      - SQLServerDatabase=datasystem
      - SQLUserName=App_Runner_Account
      - SQLPassword=Test2Alpha212!
    ports:
      - 9080:8080
    image: api
    container_name: api
    restart: always
    volumes:
      - apilog:/app/logs
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - api-network
      - app-network
      - db-network
      - message-network
      - security-network
