---
version: '3'

services:
  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
      - api-network
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: webapp
    container_name: webapp
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
      - proxy
    networks:
      - app-network