name: API Docker Image Deploy
on:
  push:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
    steps:
    - uses: actions/checkout@v4
    - name: Build the API Docker image
      run: docker build . --file Dockerfile --tag dnprogramming/api:latest
      working-directory: ${{ env.working-directory}}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the API Docker image
      run: docker push dnprogramming/api:latest