name: API Docker Image Deploy
on:
  push:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./api
      git_hash: $(git rev-parse --short "$GITHUB_SHA")
    steps:
        - uses: actions/checkout@v4
        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            repository: dnprogramming
            tags: api:latest
            file: api/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      