name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./ai
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyink
      working-directory: ${{ env.working-directory }}
    - name: Analysing the code with pyink
      run: |
        pyink $(git ls-files '*.py')
      working-directory: ${{ env.working-directory }}
